# Generated by Django 3.1.7 on 2021-05-21 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_history_listen'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='views',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='history_listen',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 16, 22, 25, 195014)),
        ),
    ]
