# Generated by Django 3.1.7 on 2021-05-21 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210521_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_listen',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 17, 1, 57, 614266)),
        ),
        migrations.AlterField(
            model_name='song',
            name='views',
            field=models.IntegerField(default=''),
        ),
    ]
