# Generated by Django 3.1.7 on 2021-05-22 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20210522_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_listen',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 12, 12, 22, 371604)),
        ),
        migrations.AlterField(
            model_name='song',
            name='views',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
