# Generated by Django 3.1.7 on 2021-05-22 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20210522_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_listen',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 12, 13, 21, 798022)),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_link',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
